### ISSUE TITLE
explain the data format of kitti_r_train_data

### ISSUE THREAD

**Issue by cloudcjf** [L1bra1/RigidFlow#1]
Hi, thanks for your work and code. I'm new to the scene flow task and training your model in debug mode for study purposes.
Could you please help me check some details?
I download the Unlabeled KITTI raw data from the link you provided. There are 6026 pair list of point clouds. It seems that you randomly choose some point clouds from different sequences rather than all the point clouds of the sequences. What's the strategy for choosing these pcs?
Also, I found that the shape of each data_pc is [N, 10]. The first three dimensions are definitely the coordinates XYZ, what about the other dimensions?

**Comment by Librae10** [comment]
Hi,

Thanks for your attention.
When we process the training point clouds in KITTI_r, we project each raw point cloud, i.e., the "velodyne_points", to the left rectified color image, i.e., the "image_02".
And we preserve the points within the image region and remove the ground points by height.
The remaining points in each frame is our training data.
The "velodyne_points" and "image_02" for each sequence can be downloaded from "[synced+rectified data]" in [https://www.cvlibs.net/datasets/kitti/raw_data.php](url).

Therefore, for each training data in the size of [N, 10], [N, 0:3] correspond to  x,y, and z coordinate of each point;
 [N, 3] correspond to the reflectance information;
 [N, 4:7] correspond to the RGB color;  
 and [N, 7:10] correspond to the surface normal, which is computed by "pptk.estimate_normals".
 
Regards,
Ruibo
