### ISSUE TITLE
Cannot reproduce result with your evaluate.py script

### ISSUE THREAD

**Issue by vacany** [L1bra1/RigidFlow#2]
Dear authors,

thank you for your work and nicely written codes. I am unable to reproduce the results with the code provided. I have downloaded the dataset, preprocess it according to the instruction. I am unpacking the Kitti scene flow testing data and using your pretrained model learned from Kitti R. I would then expect the results based on the Table 3

![image](https://user-images.githubusercontent.com/32822411/223447668-113c2128-24b0-4fba-a1de-f924299b6823.png)

However, when I load model, change the paths and dataset (set it to Kitti_s) according to instructions, I get EPE3D of 0.2092 and other metrics also lower. According to the table 3. it should be EPE3D of 0.117.

![image](https://user-images.githubusercontent.com/32822411/223448286-ab8428e5-5e6e-46a6-8511-8d9880482fa7.png)

Can you please provided some comment on that or point me what I am doing differently?

best regards,
Patrik

**Comment by Librae10** [comment]
Hi Patrik,

Thanks for your attention.
In the datasets part of the Section 5 in our paper, we denote the last 50 test pairs of KITTI_o data as KITTI_t. 
Therefore, when evaluating “FLOT_2048.pth” on KITTI_t, you can follow the steps: 
1) change the Line 40 in “datasets/KITTI_o_test.py” as 
`self.datapath = sorted(self.datapath)[100:]`

2) remove "the restriction to 35m". 
You can remove the codes from Line 56 to Line 60 in “datasets/KITTI_o_test.py”. 

3) Evaluate the pre-trained model, “FLOT_2048.pth”, on KITTI_t: 
`python evaluate.py config_evaluate_KITTI_o.yaml`

Here is the result:
![results](https://github.com/L1bra1/RigidFlow/assets/107676823/59908e45-fde3-4e64-b23a-bef1e1f29c12)

Regards,
Ruibo
